#!/usr/bin/php
<?php
$curport=0;
$handle = @fopen($argv[1], "r");
if ($handle) {
    while (($buffer = fgets($handle, 4096)) !== false) {
        if(strpos($buffer,' PREROUTING')!==false){
		$barr=explode(" ",$buffer);

		if($barr[9] != $curport){
			if($curport!=0) echo "\n";
			$curport=$barr[9]+0;
			$dr=explode(":",$barr[17]);
			echo $barr[9]." ".$dr[0]." ".trim($dr[1])." ".$barr[13]." 0 ".$barr[3];
		}
		else echo " ".$barr[3];	
	}
    }
    if (!feof($handle)) {
        echo "Error: unexpected fgets() fail\n";
    }
    fclose($handle);
}
?>
