#!/usr/bin/php
<?php
$curport=0;
$mapflag=0;
$firstrulerestored = 0;
@unlink("root/nf/.cache");

$descriptorspec = array(
   0 => array("pipe", "r"),
   1 => array("pipe", "w")
);

$process = proc_open("xtables-multi iptables-restore", $descriptorspec, $pipes);
$stdin = fopen('php://stdin', 'r');
$cachefile = fopen("/root/nf/.cache",'w');
if(!is_resource($process) || !is_resource($stdin) || !is_resource($cachefile)) {echo "Something Unexpected happened\n";goto cls;}

    while (($buffer = fgets($stdin, 4096)) !== false) {
        if(strpos($buffer,'-A PREROUTING -s ')!==false){
			if($firstrulerestored == 0) {fwrite($pipes[0],$buffer);$firstrulerestored = 1;}
			$barr=explode(" ",$buffer);
			$allips=explode(",",$barr[3]);
			$dr=explode(":",$barr[13]);
			fwrite($cachefile,$barr[9]." ".$dr[0]." ".trim($dr[1])." ".substr(trim($barr[17]),1,-1)." 0");
			foreach($allips as $ip) fwrite($cachefile," ".$ip);
			fwrite($cachefile,"\n");
		}
		else fwrite($pipes[0],$buffer);
    }
    if (!feof($stdin)) {
        echo "Error: unexpected fgets() fail\n";
    }
cls:
if(is_resource($pipes[0]))fclose($pipes[0]);
if(is_resource($pipes[1]))fclose($pipes[1]);
if(is_resource($process))proc_close($process);
if(is_resource($stdin))fclose($stdin);
if(is_resource($cachefile))fclose($cachefile);
exec("/root/nf/cli/pkfmap /root/nf/.cache");

//Do it always
exec("sysctl -w net.netfilter.nf_conntrack_tcp_loose=0");
exec("sysctl -w net.netfilter.nf_conntrack_tcp_timeout_time_wait=1");
exec("sysctl -w net.netfilter.nf_conntrack_tcp_timeout_established=60");
?>
